---
backend: pacman
skip_if_no_internet: false
update_db: false
ignore_update_db_error: false
update_system: false
pacman:
  num_retries: 0
  disable_download_timeout: false
  needed_only: false
operations:
  - remove:
      - mimos-live-environment
      - mimos-installer
      - mimos-calamares-config
      - calamares
      - mkinitcpio-archiso
      - arch-install-scripts
      - archinstall
      - clonezilla
      - cloud-init
      - darkhttpd
      - livecd-sounds
