---
units:
  - name: NetworkManager.service
    action: enable
    mandatory: true
  - name: bluetooth.service
    action: enable
    mandatory: false
  - name: firewalld.service
    action: enable
    mandatory: true
  - name: sddm.service
    action: enable
    mandatory: true
  - name: graphical.target
    action: set-default
    mandatory: true
  - name: mimos-live-setup.service
    action: disable
    mandatory: false
  - name: systemd-networkd.service
    action: disable
    mandatory: false
  - name: systemd-networkd.socket
    action: disable
    mandatory: false
