import QtQuick 2.15
import calamares.slideshow 1.0

Presentation {
    id: presentation

    // >>> generated palette tokens >>>
    // Generated by scripts/generate-calamares-style.py -- do not edit by hand.
    // Every value is a role from the mimos-claro theme or a canonical colour;
    // make check re-derives each one from palette.json and fails on drift.
    // Besito is decorative only here: as text on these grounds it fails AA.
    readonly property color slideTop: "#F5F1FE"     // roles.viewBackgroundAlternate
    readonly property color slideBottom: "#EDE7FA"  // roles.windowBackgroundAlternate
    readonly property color ink: "#221B3A"          // roles.windowForeground
    readonly property color inkSoft: "#565070"      // roles.inactiveForeground
    readonly property color accent: "#FF6FAE"       // canonical.besito
    // <<< generated palette tokens <<<

    Timer {
        interval: 6500
        running: presentation.activatedInCalamares
        repeat: true
        onTriggered: presentation.goToNextSlide()
    }

    // One layout, four slides. Each slide paints its own background because a
    // Presentation Slide has none of its own, and the gradient matches the
    // window behind it so the slideshow does not read as a pasted rectangle.

    Slide {
        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0; color: presentation.slideTop }
                GradientStop { position: 1; color: presentation.slideBottom }
            }

            Image {
                id: mimiHero
                anchors.horizontalCenter: parent.horizontalCenter
                anchors.verticalCenter: parent.verticalCenter
                anchors.verticalCenterOffset: -Math.round(parent.height * 0.12)
                width: Math.round(Math.min(parent.height * 0.42, 260))
                height: width
                sourceSize.width: 512
                sourceSize.height: 512
                fillMode: Image.PreserveAspectFit
                source: "mimi.svg"
            }

            Text {
                anchors.horizontalCenter: parent.horizontalCenter
                anchors.top: mimiHero.bottom
                anchors.topMargin: 32
                width: Math.round(parent.width * 0.78)
                horizontalAlignment: Text.AlignHCenter
                wrapMode: Text.WordWrap
                color: presentation.ink
                font.family: "Inter"
                font.pixelSize: 30
                font.weight: Font.DemiBold
                text: "Tu ordenador también merece unos mimos"
            }
        }
    }

    Slide {
        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0; color: presentation.slideTop }
                GradientStop { position: 1; color: presentation.slideBottom }
            }

            Column {
                anchors.centerIn: parent
                width: Math.round(parent.width * 0.72)
                spacing: 18

                Text {
                    width: parent.width
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                    color: presentation.ink
                    font.family: "Inter"
                    font.pixelSize: 34
                    font.weight: Font.DemiBold
                    text: "Un hogar acogedor"
                }

                Rectangle {
                    anchors.horizontalCenter: parent.horizontalCenter
                    width: 56
                    height: 4
                    radius: 2
                    color: presentation.accent
                }

                Text {
                    width: parent.width
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                    color: presentation.inkSoft
                    font.family: "Inter"
                    font.pixelSize: 20
                    text: "KDE Plasma sobre Wayland, en español desde el " +
                          "primer arranque, y la solidez de Arch Linux debajo."
                }
            }
        }
    }

    Slide {
        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0; color: presentation.slideTop }
                GradientStop { position: 1; color: presentation.slideBottom }
            }

            Column {
                anchors.centerIn: parent
                width: Math.round(parent.width * 0.72)
                spacing: 18

                Text {
                    width: parent.width
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                    color: presentation.ink
                    font.family: "Inter"
                    font.pixelSize: 34
                    font.weight: Font.DemiBold
                    text: "Actualizaciones firmadas"
                }

                Rectangle {
                    anchors.horizontalCenter: parent.horizontalCenter
                    width: 56
                    height: 4
                    radius: 2
                    color: presentation.accent
                }

                Text {
                    width: parent.width
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                    color: presentation.inkSoft
                    font.family: "Inter"
                    font.pixelSize: 20
                    text: "Cada actualización de MimOS se comprueba con la " +
                          "clave del proyecto antes de tocar tu equipo."
                }
            }
        }
    }

    Slide {
        Rectangle {
            anchors.fill: parent
            gradient: Gradient {
                GradientStop { position: 0; color: presentation.slideTop }
                GradientStop { position: 1; color: presentation.slideBottom }
            }

            Column {
                anchors.centerIn: parent
                width: Math.round(parent.width * 0.72)
                spacing: 20

                Image {
                    anchors.horizontalCenter: parent.horizontalCenter
                    width: 150
                    height: 150
                    sourceSize.width: 512
                    sourceSize.height: 512
                    fillMode: Image.PreserveAspectFit
                    source: "mimi.svg"
                }

                Text {
                    width: parent.width
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                    color: presentation.ink
                    font.family: "Inter"
                    font.pixelSize: 34
                    font.weight: Font.DemiBold
                    text: "Ya casi está"
                }

                Text {
                    width: parent.width
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                    color: presentation.inkSoft
                    font.family: "Inter"
                    font.pixelSize: 20
                    text: "Al terminar, Centro de MimOS te enseñará tu nuevo hogar."
                }
            }
        }
    }

    function onActivate() {
        presentation.currentSlide = 0
    }

    function onLeave() {
    }
}
