// Packaged as mimos-welcome-live. Live context only: Calamares removes this
// package at installation, so an installed system never carries this file
// (ADR-093).
pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    id: root

    objectName: "welcomeLiveView"
    width: 960
    height: 680
    focus: true

    property bool darkAppearance: false

    // The release channel, shown in the badge. It is a literal because this
    // view has no file capability by contract and so cannot read
    // /etc/mimos-release itself; check-welcome-contract.sh derives the
    // expected value from VERSION and fails when the two drift.
    readonly property string releaseChannel: "BETA"

    signal closeRequested()
    signal installerRequested()

    // mimos-palette-begin
    // Generated by scripts/generate-color-schemes.py from
    // packages/mimos-branding/palette.json. Do not edit by hand;
    // claro values come from the mimos-claro roles and oscuro from
    // mimos-oscuro; the launcher picks the side via
    // --mimos-appearance (ADR-093).
    readonly property color ground: root.darkAppearance ? "#221B3A" : "#FFE9F3"
    readonly property color panel: root.darkAppearance ? "#2C2444" : "#FFD3E5"
    readonly property color panelRaised: root.darkAppearance ? "#3A3058" : "#FFFFFF"
    readonly property color ink: root.darkAppearance ? "#F8F4FF" : "#221B3A"
    readonly property color inkMuted: root.darkAppearance ? "#B6ADCE" : "#7A5670"
    readonly property color hug: root.darkAppearance ? "#B3A2FF" : "#5B3BE0"
    readonly property color kiss: "#FF6FAE"
    readonly property color calm: root.darkAppearance ? "#70D6C5" : "#136B5B"
    // mimos-palette-end

    readonly property color edge: Qt.alpha(root.ink, 0.14)

    component MimosButton: Button {
        id: control

        implicitHeight: 40
        leftPadding: 18
        rightPadding: 18
        font.bold: true
        // Qt Quick buttons activate on Space alone; the footer promises
        // Enter, so Enter delivers.
        Keys.onReturnPressed: control.clicked()
        Keys.onEnterPressed: control.clicked()

        contentItem: Text {
            text: control.text
            color: control.enabled ? root.ink : root.inkMuted
            font: control.font
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }

        background: Rectangle {
            radius: 10
            color: control.down ? root.panel
                                : control.hovered ? root.panelRaised
                                                  : root.panel
            border.color: control.activeFocus ? root.calm : root.edge
            border.width: control.activeFocus ? 2 : 1
        }
    }

    component CommunityRow: RowLayout {
        id: row

        property string glyph
        property string label
        property string value

        spacing: 10

        Text {
            text: row.glyph
            font.pixelSize: 20
        }

        Text {
            text: row.label
            color: root.ink
            font.pixelSize: 14
            font.bold: true
        }

        // Plain selectable text on purpose: nobody signs into wifi or
        // Discord inside a Live session, so the links are written out to be
        // read or typed on a phone rather than opened here (ADR-093).
        TextEdit {
            Layout.fillWidth: true
            text: row.value
            color: root.hug
            font.pixelSize: 14
            readOnly: true
            selectByMouse: true
        }
    }

    Rectangle {
        anchors.fill: parent
        color: root.ground

        ScrollView {
            id: livePage
            anchors.fill: parent
            anchors.margins: 22
            clip: true
            ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

            ColumnLayout {
                width: livePage.availableWidth
                spacing: 10

                Image {
                    Layout.alignment: Qt.AlignHCenter
                    Layout.preferredWidth: 112
                    Layout.preferredHeight: 112
                    source: "file:///usr/share/mimos/branding/mimi.svg"
                    sourceSize.width: 264
                    sourceSize.height: 264
                    fillMode: Image.PreserveAspectFit
                }

                Text {
                    Layout.alignment: Qt.AlignHCenter
                    textFormat: Text.StyledText
                    // The OS in Besito is the logotype treatment; on light
                    // grounds it is a recorded brand exemption, never a
                    // licence for Besito body text.
                    text: "Bienvenido a Mim<font color=\""
                          + root.kiss + "\">OS</font>"
                    color: root.ink
                    font.pixelSize: 34
                    font.bold: true
                }

                Text {
                    Layout.alignment: Qt.AlignHCenter
                    text: "Tu ordenador también merece unos mimos"
                    color: root.hug
                    font.pixelSize: 15
                    font.bold: true
                }

                Rectangle {
                    Layout.alignment: Qt.AlignHCenter
                    radius: 12
                    color: root.panel
                    border.color: root.edge
                    border.width: 1
                    implicitWidth: releaseLabel.implicitWidth + 28
                    implicitHeight: 30

                    Text {
                        id: releaseLabel
                        objectName: "releaseLabel"
                        anchors.centerIn: parent
                        text: root.releaseChannel + " · ENTORNO LIVE"
                        color: root.ink
                        font.pixelSize: 11
                        font.bold: true
                    }
                }

                Text {
                    objectName: "homeIntro"
                    Layout.alignment: Qt.AlignHCenter
                    Layout.fillWidth: true
                    text: "Gracias por probar MimOS. Explora KDE Plasma con calma: nada de lo que hagas aquí toca tus discos."
                    color: root.inkMuted
                    font.pixelSize: 14
                    horizontalAlignment: Text.AlignHCenter
                    wrapMode: Text.WordWrap
                }

                Rectangle {
                    Layout.fillWidth: true
                    Layout.topMargin: 6
                    implicitHeight: safeColumn.implicitHeight + 36
                    radius: 18
                    color: root.panel
                    border.color: root.edge
                    border.width: 1

                    ColumnLayout {
                        id: safeColumn
                        anchors.fill: parent
                        anchors.margins: 18
                        spacing: 6

                        Text {
                            objectName: "contextCardTitle"
                            text: "Un espacio seguro para probar"
                            color: root.ink
                            font.pixelSize: 18
                            font.bold: true
                        }

                        Text {
                            objectName: "contextCardBody"
                            Layout.fillWidth: true
                            text: "Puedes probar MimOS sin tocar el disco. Si decides instalarlo, el instalador sí modifica el disco que elijas."
                            color: root.inkMuted
                            font.pixelSize: 14
                            wrapMode: Text.WordWrap
                        }
                    }
                }

                Button {
                    id: installerButton
                    objectName: "installerButton"
                    Layout.alignment: Qt.AlignHCenter
                    Layout.preferredWidth: 300
                    implicitHeight: 84
                    text: "Instalar MimOS"
                    Accessible.name: text
                    Accessible.description: "Abre el instalador, que modificará el disco que elijas"
                    Keys.onReturnPressed: installerButton.clicked()
                    Keys.onEnterPressed: installerButton.clicked()
                    onClicked: root.installerRequested()

                    contentItem: ColumnLayout {
                        spacing: 6

                        Text {
                            Layout.alignment: Qt.AlignHCenter
                            text: "💜"
                            font.pixelSize: 28
                        }

                        Text {
                            Layout.alignment: Qt.AlignHCenter
                            text: installerButton.text
                            color: root.ink
                            font.pixelSize: 15
                            font.bold: true
                            horizontalAlignment: Text.AlignHCenter
                        }
                    }

                    background: Rectangle {
                        radius: 16
                        color: installerButton.down ? root.panel
                                                    : installerButton.hovered ? root.panelRaised
                                                                              : root.panel
                        border.color: installerButton.activeFocus ? root.calm : root.edge
                        border.width: installerButton.activeFocus ? 2 : 1
                    }
                }

                Rectangle {
                    Layout.fillWidth: true
                    implicitHeight: communityColumn.implicitHeight + 32
                    radius: 16
                    color: root.panel
                    border.color: root.edge
                    border.width: 1

                    ColumnLayout {
                        id: communityColumn
                        anchors.fill: parent
                        anchors.margins: 14
                        spacing: 6

                        CommunityRow {
                            objectName: "websiteRow"
                            Layout.fillWidth: true
                            glyph: "🌐"
                            label: "Sitio web"
                            value: "mimoslinux.org"
                        }

                        CommunityRow {
                            objectName: "discordRow"
                            Layout.fillWidth: true
                            glyph: "💬"
                            label: "Discord de MimOS"
                            value: "discord.gg/RQ4ftnb9mB"
                        }

                        CommunityRow {
                            objectName: "sourcesRow"
                            Layout.fillWidth: true
                            glyph: "🧡"
                            label: "Código fuente"
                            value: "github.com/DavidFB-creator"
                        }
                    }
                }

                RowLayout {
                    Layout.fillWidth: true

                    Text {
                        Layout.fillWidth: true
                        text: "Tab navegar · Enter activar · Esc cerrar"
                        color: root.inkMuted
                        font.pixelSize: 12
                    }

                    Text {
                        text: "powered by XI14"
                        color: root.inkMuted
                        font.pixelSize: 12
                        font.bold: true
                    }

                    MimosButton {
                        id: closeButton
                        objectName: "closeButton"
                        text: "Cerrar"
                        Accessible.name: text
                        onClicked: root.closeRequested()
                    }
                }
            }
        }
    }

    Keys.onEscapePressed: event => {
        root.closeRequested()
        event.accepted = true
    }

    Component.onCompleted: Qt.callLater(installerButton.forceActiveFocus)
}
