// Generated by scripts/generate-plasma-lookandfeel.py from
// packages/mimos-branding/palette.json (mimos-claro). Do not edit by hand;
// edit the palette and regenerate, or make check will fail.
//
// The stage API and the animation-disabling guard follow Breeze's
// Splash.qml as shipped in plasma-workspace: stage 2 fades the content in,
// stage 5 fades the busy cue out, and a Kirigami duration of 1 or less
// means the user has disabled animations.

import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {
    id: root

    property int stage

    gradient: Gradient {
        GradientStop { position: 0.0; color: "#FFEFF6" }
        GradientStop { position: 1.0; color: "#FFD3E5" }
    }

    onStageChanged: {
        if (stage == 2) {
            introAnimation.running = true;
        } else if (stage == 5) {
            introAnimation.target = breathing;
            introAnimation.from = 1;
            introAnimation.to = 0;
            introAnimation.running = true;
        }
    }

    Item {
        id: content
        anchors.fill: parent
        opacity: 0

        Item {
            id: breathing
            anchors.centerIn: parent
            width: mimi.width
            height: mimi.height

            Image {
                id: mimi
                anchors.centerIn: parent
                asynchronous: true
                source: "images/mimi.svg"
                sourceSize.width: Kirigami.Units.gridUnit * 8
                sourceSize.height: Kirigami.Units.gridUnit * 8
            }

            // MIMI breathes while the session loads: the motion is the busy
            // cue, so it must stop entirely when animations are disabled --
            // a still MIMI is a fine splash, a frozen mid-breath scale is
            // not.
            SequentialAnimation on scale {
                loops: Animation.Infinite
                running: Kirigami.Units.longDuration > 1
                NumberAnimation {
                    from: 1.0
                    to: 1.05
                    duration: 1200
                    easing.type: Easing.InOutQuad
                }
                NumberAnimation {
                    from: 1.05
                    to: 1.0
                    duration: 1200
                    easing.type: Easing.InOutQuad
                }
            }
        }

        Image {
            id: wordmark
            anchors.horizontalCenter: parent.horizontalCenter
            y: breathing.y + breathing.height + Kirigami.Units.gridUnit
            asynchronous: true
            source: "images/mimos-wordmark.svg"
            sourceSize.height: Kirigami.Units.gridUnit * 2
        }
    }

    OpacityAnimator {
        id: introAnimation
        running: false
        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }
}
