// Generated by scripts/generate-plasma-lookandfeel.py. Do not edit by hand;
// edit the generator and regenerate, or make check will fail.
//
// ONE splash, black, for both Global Themes. David's call on 2026-08-10:
// the session start should not have an appearance. There were two before,
// each carrying its theme's gradient, and the switch between them happened
// in the half second before the desktop drew -- so a person changing from
// claro to oscuro saw the transition twice, once in a screen that exists
// only to say "wait".
//
// Black rather than Noche, and that is a deliberate departure from the
// palette rather than an oversight: this ground is not a surface the design
// system dresses, it is the absence of one. It is also the only value that
// looks identical on every panel, which is what "no appearance" means in
// practice. Both variants therefore carry the dark-surface wordmark master,
// because the surface is dark whichever theme is on.
//
// The stage API and the animation-disabling guard follow Breeze's
// Splash.qml as shipped in plasma-workspace: stage 2 fades the content in,
// stage 5 fades the busy cue out, and a Kirigami duration of 1 or less
// means the user has disabled animations.

import QtQuick
import org.kde.kirigami as Kirigami

Rectangle {
    id: root

    property int stage

    color: "#000000"

    onStageChanged: {
        if (stage == 2) {
            introAnimation.running = true;
        } else if (stage == 5) {
            introAnimation.target = breathing;
            introAnimation.from = 1;
            introAnimation.to = 0;
            introAnimation.running = true;
        }
    }

    Item {
        id: content
        anchors.fill: parent
        opacity: 0

        Item {
            id: breathing
            anchors.centerIn: parent
            width: mimi.width
            height: mimi.height

            Image {
                id: mimi
                anchors.centerIn: parent
                asynchronous: true
                source: "images/mimi.svg"
                sourceSize.width: Kirigami.Units.gridUnit * 8
                sourceSize.height: Kirigami.Units.gridUnit * 8
            }

            // MIMI breathes while the session loads: the motion is the busy
            // cue, so it must stop entirely when animations are disabled --
            // a still MIMI is a fine splash, a frozen mid-breath scale is
            // not.
            SequentialAnimation on scale {
                loops: Animation.Infinite
                running: Kirigami.Units.longDuration > 1
                NumberAnimation {
                    from: 1.0
                    to: 1.05
                    duration: 1200
                    easing.type: Easing.InOutQuad
                }
                NumberAnimation {
                    from: 1.05
                    to: 1.0
                    duration: 1200
                    easing.type: Easing.InOutQuad
                }
            }
        }

        Image {
            id: wordmark
            anchors.horizontalCenter: parent.horizontalCenter
            y: breathing.y + breathing.height + Kirigami.Units.gridUnit
            asynchronous: true
            source: "images/mimos-wordmark-dark.svg"
            sourceSize.height: Kirigami.Units.gridUnit * 2
        }
    }

    OpacityAnimator {
        id: introAnimation
        running: false
        target: content
        from: 0
        to: 1
        duration: Kirigami.Units.veryLongDuration * 2
        easing.type: Easing.InOutQuad
    }
}
