// Packaged as mimos-welcome. Installed context only: the Live experience
// lives in mimos-welcome-live, which Calamares removes at installation
// (ADR-093).
pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    id: root

    objectName: "welcomeView"
    width: 960
    height: 680
    focus: true

    property int currentPage: 0
    property bool showAfterUpdates: true
    property bool includeHardwareDetails: false
    property bool includeRecentLogs: false
    property bool darkAppearance: false

    // The release channel, shown in the badge. It is a literal because this
    // view has no file capability by contract and so cannot read
    // /etc/mimos-release itself -- but check-welcome-contract.sh derives the
    // expected value from VERSION and fails when the two drift, so it cannot
    // silently go stale again. It said ALPHA through three betas, and the
    // contract pinned that string as a required fragment, which meant the
    // checker was guaranteeing the wrong answer rather than catching it.
    readonly property string releaseChannel: "BETA"

    signal closeRequested()
    signal themeRequested(string variant)
    signal discoverRequested()

    // mimos-palette-begin
    // Generated by scripts/generate-color-schemes.py from
    // packages/mimos-branding/palette.json. Do not edit by hand;
    // claro values come from the mimos-claro roles and oscuro from
    // mimos-oscuro; the launcher picks the side via
    // --mimos-appearance (ADR-093).
    readonly property color ground: root.darkAppearance ? "#221B3A" : "#FFE9F3"
    readonly property color panel: root.darkAppearance ? "#2C2444" : "#FFD3E5"
    readonly property color panelRaised: root.darkAppearance ? "#3A3058" : "#FFFFFF"
    readonly property color ink: root.darkAppearance ? "#F8F4FF" : "#221B3A"
    readonly property color inkMuted: root.darkAppearance ? "#B6ADCE" : "#7A5670"
    readonly property color hug: root.darkAppearance ? "#B3A2FF" : "#5B3BE0"
    readonly property color kiss: "#FF6FAE"
    readonly property color calm: root.darkAppearance ? "#70D6C5" : "#136B5B"
    // mimos-palette-end

    readonly property color edge: Qt.alpha(root.ink, 0.14)

    component MimosButton: Button {
        id: control

        implicitHeight: 40
        leftPadding: 18
        rightPadding: 18
        font.bold: true
        // Qt Quick buttons activate on Space alone; the footer promises
        // Enter, so Enter delivers.
        Keys.onReturnPressed: control.clicked()
        Keys.onEnterPressed: control.clicked()

        contentItem: Text {
            text: control.text
            color: control.enabled ? root.ink : root.inkMuted
            font: control.font
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }

        background: Rectangle {
            radius: 10
            color: control.down ? root.panel
                                : control.hovered ? root.panelRaised
                                                  : root.panel
            border.color: control.activeFocus ? root.calm : root.edge
            border.width: control.activeFocus ? 2 : 1
        }
    }

    component MimosCard: Button {
        id: control

        property string glyph
        property string caption

        implicitHeight: 116
        Layout.fillWidth: true
        // Equal columns: without a uniform preferred width the grid sizes
        // each column to its longest label and the six cards come out
        // unequal, which David rejected on screen.
        Layout.preferredWidth: 1
        Accessible.name: control.text
        Accessible.description: control.caption
        Keys.onReturnPressed: control.clicked()
        Keys.onEnterPressed: control.clicked()

        contentItem: ColumnLayout {
            spacing: 6

            Text {
                Layout.alignment: Qt.AlignHCenter
                text: control.glyph
                font.pixelSize: 30
            }

            Text {
                Layout.alignment: Qt.AlignHCenter
                Layout.fillWidth: true
                text: control.text
                color: root.ink
                font.pixelSize: 15
                font.bold: true
                horizontalAlignment: Text.AlignHCenter
                wrapMode: Text.WordWrap
            }
        }

        background: Rectangle {
            radius: 16
            color: control.down ? root.panel
                                : control.hovered ? root.panelRaised
                                                  : root.panel
            border.color: control.activeFocus ? root.calm : root.edge
            border.width: control.activeFocus ? 2 : 1
        }
    }

    component PrivacySwitch: SwitchDelegate {
        id: control

        implicitHeight: 52
        leftPadding: 16
        rightPadding: 16
        spacing: 16

        contentItem: Item {
            implicitWidth: 1

            Text {
                anchors.fill: parent
                rightPadding: control.indicator.width + control.spacing
                text: control.text
                color: root.ink
                font.pixelSize: 14
                font.bold: true
                verticalAlignment: Text.AlignVCenter
                wrapMode: Text.WordWrap
            }
        }

        indicator: Rectangle {
            implicitWidth: 48
            implicitHeight: 28
            x: control.width - width - control.rightPadding
            y: control.topPadding + (control.availableHeight - height) / 2
            radius: height / 2
            color: control.checked ? root.calm : root.inkMuted
            border.color: control.activeFocus ? root.ink : "transparent"
            border.width: 2

            Rectangle {
                width: 20
                height: 20
                radius: 10
                y: 4
                x: control.checked ? parent.width - width - 4 : 4
                color: root.panelRaised

                Behavior on x {
                    NumberAnimation {
                        duration: 120
                    }
                }
            }
        }

        background: Rectangle {
            radius: 14
            color: control.hovered ? root.panelRaised : root.panel
            border.color: control.activeFocus ? root.calm : root.edge
            border.width: control.activeFocus ? 2 : 1
        }
    }

    component BackButton: MimosButton {
        text: "← Volver"
        Accessible.name: "Volver a la portada"
        onClicked: root.showPage(0)
    }

    function focusCurrentPage() {
        if (currentPage === 0) {
            firstStepsCard.forceActiveFocus()
        } else {
            backFocusTarget()
        }
    }

    function backFocusTarget() {
        if (currentPage === 1) {
            stepsBack.forceActiveFocus()
        } else if (currentPage === 2) {
            claroButton.forceActiveFocus()
        } else if (currentPage === 3) {
            updatesSwitch.forceActiveFocus()
        } else {
            supportBack.forceActiveFocus()
        }
    }

    function showPage(page) {
        currentPage = page
        Qt.callLater(focusCurrentPage)
    }

    function resetPrivacy() {
        showAfterUpdates = true
        includeHardwareDetails = false
        includeRecentLogs = false
    }

    Rectangle {
        anchors.fill: parent
        color: root.ground

        ColumnLayout {
            anchors.fill: parent
            anchors.margins: 28
            spacing: 14

            StackLayout {
                Layout.fillWidth: true
                Layout.fillHeight: true
                Layout.minimumWidth: 0
                currentIndex: root.currentPage

                // ---- Portada -------------------------------------------------
                ScrollView {
                    id: homePage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: homePage.availableWidth
                        spacing: 14

                        Image {
                            Layout.alignment: Qt.AlignHCenter
                            Layout.preferredWidth: 132
                            Layout.preferredHeight: 132
                            source: "file:///usr/share/mimos/branding/mimi.svg"
                            sourceSize.width: 264
                            sourceSize.height: 264
                            fillMode: Image.PreserveAspectFit
                        }

                        Text {
                            Layout.alignment: Qt.AlignHCenter
                            textFormat: Text.StyledText
                            // The OS in Besito is the logotype treatment; on
                            // light grounds it is a recorded brand exemption,
                            // never a licence for Besito body text.
                            text: "Bienvenido a Mim<font color=\""
                                  + root.kiss + "\">OS</font>"
                            color: root.ink
                            font.pixelSize: 34
                            font.bold: true
                        }

                        Text {
                            Layout.alignment: Qt.AlignHCenter
                            text: "Tu ordenador también merece unos mimos"
                            color: root.hug
                            font.pixelSize: 15
                            font.bold: true
                        }

                        Rectangle {
                            Layout.alignment: Qt.AlignHCenter
                            radius: 12
                            color: root.panel
                            border.color: root.edge
                            border.width: 1
                            implicitWidth: releaseLabel.implicitWidth + 28
                            implicitHeight: 30

                            Text {
                                id: releaseLabel
                                objectName: "releaseLabel"
                                anchors.centerIn: parent
                                text: root.releaseChannel + " · INSTALADO"
                                color: root.ink
                                font.pixelSize: 11
                                font.bold: true
                            }
                        }

                        Text {
                            objectName: "homeIntro"
                            Layout.alignment: Qt.AlignHCenter
                            Layout.fillWidth: true
                            text: "Gracias por instalar MimOS. Este es tu nuevo hogar: desde aquí puedes dar los primeros pasos y dejarlo todo a tu gusto."
                            color: root.inkMuted
                            font.pixelSize: 14
                            horizontalAlignment: Text.AlignHCenter
                            wrapMode: Text.WordWrap
                        }

                        GridLayout {
                            Layout.fillWidth: true
                            Layout.topMargin: 6
                            columns: 3
                            columnSpacing: 14
                            rowSpacing: 14

                            MimosCard {
                                id: firstStepsCard
                                objectName: "firstStepsCard"
                                glyph: "🚀"
                                text: "Primeros pasos"
                                caption: "Una guía corta para estrenar tu sistema"
                                onClicked: root.showPage(1)
                            }

                            MimosCard {
                                objectName: "discoverCard"
                                glyph: "🛍️"
                                text: "Instalar aplicaciones"
                                caption: "Abre Discover, la tienda de aplicaciones de KDE"
                                onClicked: root.discoverRequested()
                            }

                            MimosCard {
                                objectName: "personalizeCard"
                                glyph: "🎨"
                                text: "Personalizar MimOS"
                                caption: "Cambia entre MimOS Claro y MimOS Oscuro"
                                onClicked: root.showPage(2)
                            }

                            MimosCard {
                                objectName: "documentationCard"
                                glyph: "📖"
                                text: "Documentación"
                                caption: "Abre mimoslinux.org en tu navegador"
                                onClicked: Qt.openUrlExternally("https://mimoslinux.org")
                            }

                            MimosCard {
                                objectName: "privacyCard"
                                glyph: "🛡️"
                                text: "Privacidad"
                                caption: "Telemetría automática desactivada; revisa tus preferencias locales"
                                onClicked: root.showPage(3)
                            }

                            MimosCard {
                                objectName: "supportCard"
                                glyph: "💗"
                                text: "Crear paquete de soporte"
                                caption: "Cómo generar un informe local con mimos-diagnostico"
                                onClicked: root.showPage(4)
                            }
                        }
                    }
                }

                // ---- Primeros pasos -----------------------------------------
                ScrollView {
                    id: stepsPage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: stepsPage.availableWidth
                        spacing: 12

                        BackButton {
                            id: stepsBack
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Primeros pasos"
                            color: root.ink
                            font.pixelSize: 26
                            font.bold: true
                        }

                        Repeater {
                            model: [
                                {
                                    title: "1 · Ponlo a tu gusto",
                                    body: "En «Personalizar MimOS» puedes cambiar entre MimOS Claro y MimOS Oscuro con un clic; el fondo de pantalla cambia contigo. Para más ajustes, abre Preferencias del sistema."
                                },
                                {
                                    title: "2 · Instala tus aplicaciones",
                                    body: "«Instalar aplicaciones» abre Discover. Busca, instala y actualiza software con unos clics; también puedes usar pacman desde la terminal."
                                },
                                {
                                    title: "3 · Mantenlo actualizado",
                                    body: "Discover te avisará de las actualizaciones. MimOS es una beta: actualiza con frecuencia y no lo uses todavía para datos importantes."
                                },
                                {
                                    title: "4 · Pide ayuda cuando quieras",
                                    body: "La comunidad está en Discord y la documentación en mimoslinux.org. Si algo falla, «Crear paquete de soporte» explica cómo preparar un informe local."
                                }
                            ]

                            delegate: Rectangle {
                                id: stepCard

                                required property var modelData

                                Layout.fillWidth: true
                                implicitHeight: stepColumn.implicitHeight + 32
                                radius: 16
                                color: root.panel
                                border.color: root.edge
                                border.width: 1

                                ColumnLayout {
                                    id: stepColumn
                                    anchors.fill: parent
                                    anchors.margins: 16
                                    spacing: 6

                                    Text {
                                        text: stepCard.modelData.title
                                        color: root.hug
                                        font.pixelSize: 16
                                        font.bold: true
                                    }

                                    Text {
                                        Layout.fillWidth: true
                                        text: stepCard.modelData.body
                                        color: root.ink
                                        font.pixelSize: 14
                                        wrapMode: Text.WordWrap
                                    }
                                }
                            }
                        }

                        MimosButton {
                            objectName: "communityButton"
                            text: "Abrir la comunidad en Discord"
                            Accessible.name: text
                            onClicked: Qt.openUrlExternally("https://discord.gg/RQ4ftnb9mB")
                        }
                    }
                }

                // ---- Personalizar -------------------------------------------
                ScrollView {
                    id: personalizePage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: personalizePage.availableWidth
                        spacing: 12

                        BackButton {
                            id: personalizeBack
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Personalizar MimOS"
                            color: root.ink
                            font.pixelSize: 26
                            font.bold: true
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Elige el tema del sistema. Se aplica al momento y esta ventana se reabrirá con el aspecto nuevo."
                            color: root.inkMuted
                            font.pixelSize: 14
                            wrapMode: Text.WordWrap
                        }

                        RowLayout {
                            Layout.fillWidth: true
                            spacing: 14

                            MimosCard {
                                id: claroButton
                                objectName: "claroButton"
                                glyph: "🌸"
                                text: "MimOS Claro"
                                caption: "Aplica el tema claro con sus rositas"
                                onClicked: root.themeRequested("claro")
                            }

                            MimosCard {
                                id: oscuroButton
                                objectName: "oscuroButton"
                                glyph: "🌙"
                                text: "MimOS Oscuro"
                                caption: "Aplica el tema oscuro sobre Noche"
                                onClicked: root.themeRequested("oscuro")
                            }
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Para fuentes, iconos y demás detalles, abre Preferencias del sistema desde el menú de aplicaciones."
                            color: root.inkMuted
                            font.pixelSize: 13
                            wrapMode: Text.WordWrap
                        }
                    }
                }

                // ---- Privacidad ---------------------------------------------
                ScrollView {
                    id: privacyPage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: privacyPage.availableWidth
                        spacing: 10

                        BackButton {
                            id: privacyBack
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Privacidad clara, sin letra pequeña"
                            color: root.ink
                            font.pixelSize: 26
                            font.bold: true
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Estas preferencias se guardan únicamente en tu perfil local. Centro de MimOS no envía ningún dato."
                            color: root.inkMuted
                            font.pixelSize: 15
                            wrapMode: Text.WordWrap
                        }

                        Rectangle {
                            Layout.fillWidth: true
                            implicitHeight: 72
                            radius: 16
                            color: root.panel
                            border.color: root.calm

                            RowLayout {
                                anchors.fill: parent
                                anchors.margins: 18
                                spacing: 16

                                Text {
                                    text: "✓"
                                    color: root.calm
                                    font.pixelSize: 28
                                    font.bold: true
                                }

                                ColumnLayout {
                                    Layout.fillWidth: true
                                    Layout.minimumWidth: 0
                                    Text {
                                        text: "Telemetría automática desactivada"
                                        color: root.ink
                                        font.pixelSize: 17
                                        font.bold: true
                                    }
                                    Text {
                                        Layout.fillWidth: true
                                        Layout.minimumWidth: 0
                                        text: "MimOS no incorpora seguimiento ni subidas silenciosas."
                                        color: root.inkMuted
                                        wrapMode: Text.WordWrap
                                    }
                                }
                            }
                        }

                        PrivacySwitch {
                            id: updatesSwitch
                            objectName: "updatesSwitch"
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Mostrar Centro de MimOS después de una actualización"
                            checked: root.showAfterUpdates
                            Accessible.name: text
                            Accessible.description: "Guarda localmente si debe mostrarse la bienvenida de una versión nueva"
                            onToggled: root.showAfterUpdates = checked
                        }

                        PrivacySwitch {
                            id: hardwareSwitch
                            objectName: "hardwareSwitch"
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Incluir un resumen del hardware en informes manuales"
                            checked: root.includeHardwareDetails
                            Accessible.name: text
                            Accessible.description: "Preferencia local, desactivada inicialmente; el informe solo se crea con mimos-diagnostico y nunca se envía solo"
                            onToggled: root.includeHardwareDetails = checked
                        }

                        PrivacySwitch {
                            id: logsSwitch
                            objectName: "logsSwitch"
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Incluir registros recientes en informes manuales"
                            checked: root.includeRecentLogs
                            Accessible.name: text
                            Accessible.description: "Preferencia local, desactivada inicialmente; el informe solo se crea con mimos-diagnostico y nunca se envía solo"
                            onToggled: root.includeRecentLogs = checked
                        }

                        Text {
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Estas opciones solo establecen valores predeterminados para mimos-diagnostico y nunca autorizan un envío."
                            color: root.inkMuted
                            font.pixelSize: 12
                            wrapMode: Text.WordWrap
                        }

                        MimosButton {
                            id: resetPrivacyButton
                            objectName: "resetPrivacyButton"
                            text: "Restablecer valores privados"
                            Accessible.name: text
                            Accessible.description: "Activa la bienvenida y desactiva la inclusión de hardware y registros"
                            onClicked: root.resetPrivacy()
                        }
                    }
                }

                // ---- Paquete de soporte -------------------------------------
                ScrollView {
                    id: supportPage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: supportPage.availableWidth
                        spacing: 12

                        BackButton {
                            id: supportBack
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Crear paquete de soporte"
                            color: root.ink
                            font.pixelSize: 26
                            font.bold: true
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Si algo falla y quieres pedir ayuda, MimOS puede preparar un informe local con los datos básicos del sistema. Se crea solo cuando tú lo pides, se guarda en tu carpeta personal y nunca se envía automáticamente."
                            color: root.inkMuted
                            font.pixelSize: 15
                            wrapMode: Text.WordWrap
                        }

                        Rectangle {
                            Layout.fillWidth: true
                            implicitHeight: supportColumn.implicitHeight + 36
                            radius: 16
                            color: root.panel
                            border.color: root.edge
                            border.width: 1

                            ColumnLayout {
                                id: supportColumn
                                anchors.fill: parent
                                anchors.margins: 18
                                spacing: 8

                                Text {
                                    text: "Abre una terminal (Konsole) y escribe:"
                                    color: root.ink
                                    font.pixelSize: 15
                                    font.bold: true
                                }

                                Rectangle {
                                    Layout.fillWidth: true
                                    implicitHeight: 44
                                    radius: 10
                                    color: root.panelRaised
                                    border.color: root.edge
                                    border.width: 1

                                    TextEdit {
                                        anchors.fill: parent
                                        anchors.margins: 12
                                        text: "mimos-diagnostico --solo-ver"
                                        color: root.ink
                                        font.family: "monospace"
                                        font.pixelSize: 14
                                        readOnly: true
                                        selectByMouse: true
                                    }
                                }

                                Text {
                                    Layout.fillWidth: true
                                    text: "«--solo-ver» muestra lo que contendría el informe sin crear nada. Cuando estés conforme, repite el comando sin esa opción y confirma: el archivo queda en tu carpeta personal, con direcciones y nombres ya tachados, listo para adjuntarlo tú donde quieras."
                                    color: root.inkMuted
                                    font.pixelSize: 14
                                    wrapMode: Text.WordWrap
                                }
                            }
                        }
                    }
                }
            }

            RowLayout {
                Layout.fillWidth: true

                Text {
                    Layout.fillWidth: true
                    text: "Tab navegar · Enter activar · Esc volver o cerrar"
                    color: root.inkMuted
                    font.pixelSize: 12
                }

                Text {
                    text: "powered by XI14"
                    color: root.inkMuted
                    font.pixelSize: 12
                    font.bold: true
                }

                MimosButton {
                    id: closeButton
                    objectName: "closeButton"
                    text: "Cerrar"
                    Accessible.name: text
                    onClicked: root.closeRequested()
                }
            }
        }
    }

    Keys.onEscapePressed: event => {
        if (root.currentPage !== 0) {
            root.showPage(0)
        } else {
            root.closeRequested()
        }
        event.accepted = true
    }

    Component.onCompleted: Qt.callLater(focusCurrentPage)
}
