// Packaged as mimos-welcome.
pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    id: root

    objectName: "welcomeView"
    width: 960
    height: 680
    focus: true

    property int currentPage: 0
    property bool showAfterUpdates: true
    property bool includeHardwareDetails: false
    property bool includeRecentLogs: false
    property bool liveEnvironment: false

    // The release channel, shown in the badge. It is a literal because this
    // view has no file capability by contract and so cannot read
    // /etc/mimos-release itself -- but check-welcome-contract.sh derives the
    // expected value from VERSION and fails when the two drift, so it cannot
    // silently go stale again. It said ALPHA through three betas, and the
    // contract pinned that string as a required fragment, which meant the
    // checker was guaranteeing the wrong answer rather than catching it.
    readonly property string releaseChannel: "BETA"

    signal closeRequested()
    signal installerRequested()

    // mimos-palette-begin
    // Generated by scripts/generate-color-schemes.py from
    // packages/mimos-branding/palette.json. Do not edit by hand;
    // values come from the mimos-oscuro roles.
    readonly property color night: "#221B3A"
    readonly property color panel: "#2C2444"
    readonly property color panelRaised: "#3A3058"
    readonly property color cloud: "#F8F4FF"
    readonly property color muted: "#B6ADCE"
    readonly property color hug: "#B3A2FF"
    readonly property color kiss: "#FF6FAE"
    readonly property color calm: "#70D6C5"
    // mimos-palette-end

    component MimosButton: Button {
        id: control

        implicitHeight: 40
        leftPadding: 18
        rightPadding: 18
        font.bold: true

        contentItem: Text {
            text: control.text
            color: control.enabled ? root.cloud : "#746A85"
            font: control.font
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }

        background: Rectangle {
            radius: 10
            color: control.down ? "#4C4069"
                                : control.hovered ? root.panelRaised
                                                  : root.panel
            border.color: control.activeFocus ? root.calm : "#5B4B78"
            border.width: control.activeFocus ? 2 : 1
        }
    }

    component MimosTabButton: TabButton {
        id: control

        implicitHeight: 44
        font.bold: true

        contentItem: Text {
            text: control.text
            color: control.checked ? root.cloud : root.muted
            font: control.font
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }

        background: Rectangle {
            radius: 10
            color: control.checked ? root.panelRaised
                                   : control.hovered ? "#33294E"
                                                     : "transparent"
            border.color: control.activeFocus ? root.calm : "transparent"
            border.width: 2
        }
    }

    component PrivacySwitch: SwitchDelegate {
        id: control

        implicitHeight: 52
        leftPadding: 16
        rightPadding: 16
        spacing: 16

        contentItem: Item {
            implicitWidth: 1

            Text {
                anchors.fill: parent
                rightPadding: control.indicator.width + control.spacing
                text: control.text
                color: root.cloud
                font.pixelSize: 14
                font.bold: true
                verticalAlignment: Text.AlignVCenter
                wrapMode: Text.WordWrap
            }
        }

        indicator: Rectangle {
            implicitWidth: 48
            implicitHeight: 28
            x: control.width - width - control.rightPadding
            y: control.topPadding + (control.availableHeight - height) / 2
            radius: height / 2
            color: control.checked ? root.calm : "#5C526D"
            border.color: control.activeFocus ? root.cloud : "transparent"
            border.width: 2

            Rectangle {
                width: 20
                height: 20
                radius: 10
                y: 4
                x: control.checked ? parent.width - width - 4 : 4
                color: control.checked ? root.night : root.cloud

                Behavior on x {
                    NumberAnimation {
                        duration: 120
                    }
                }
            }
        }

        background: Rectangle {
            radius: 14
            color: control.hovered ? root.panelRaised : root.panel
            border.color: control.activeFocus ? root.calm : "#4C4069"
            border.width: control.activeFocus ? 2 : 1
        }
    }

    function focusCurrentPage() {
        if (currentPage === 0) {
            homeTab.forceActiveFocus()
        } else if (currentPage === 1) {
            privacyTab.forceActiveFocus()
        } else {
            aboutTab.forceActiveFocus()
        }
    }

    function showPage(page) {
        currentPage = page
        Qt.callLater(focusCurrentPage)
    }

    function resetPrivacy() {
        showAfterUpdates = true
        includeHardwareDetails = false
        includeRecentLogs = false
    }

    Rectangle {
        anchors.fill: parent
        color: root.night

        ColumnLayout {
            anchors.fill: parent
            anchors.margins: 28
            spacing: 18

            RowLayout {
                Layout.fillWidth: true
                spacing: 14

                Rectangle {
                    Layout.preferredWidth: 46
                    Layout.preferredHeight: 46
                    radius: 14
                    color: root.kiss

                    Text {
                        anchors.centerIn: parent
                        text: "♥"
                        color: root.night
                        font.pixelSize: 24
                        font.bold: true
                    }
                }

                ColumnLayout {
                    Layout.fillWidth: true
                    spacing: 2

                    Text {
                        text: "Centro de MimOS"
                        color: root.cloud
                        font.pixelSize: 25
                        font.bold: true
                    }

                    Text {
                        text: "Tu ordenador también merece unos mimos"
                        color: root.muted
                        font.pixelSize: 14
                    }
                }

                Rectangle {
                    radius: 12
                    color: "#183D38"
                    border.color: root.calm
                    border.width: 1
                    implicitWidth: releaseLabel.implicitWidth + 28
                    implicitHeight: 32

                    Text {
                        id: releaseLabel
                        objectName: "releaseLabel"
                        anchors.centerIn: parent
                        text: root.liveEnvironment
                              ? root.releaseChannel + " · ENTORNO LIVE"
                              : root.releaseChannel + " · INSTALADO"
                        color: root.calm
                        font.pixelSize: 11
                        font.bold: true
                    }
                }
            }

            TabBar {
                id: navigation
                Layout.fillWidth: true
                currentIndex: root.currentPage
                onCurrentIndexChanged: root.currentPage = currentIndex

                background: Rectangle {
                    color: root.panel
                    radius: 12
                }

                MimosTabButton {
                    id: homeTab
                    objectName: "homeTab"
                    text: "Inicio"
                    Accessible.name: text
                    onClicked: root.showPage(0)
                }

                MimosTabButton {
                    id: privacyTab
                    objectName: "privacyTab"
                    text: "Privacidad"
                    Accessible.name: text
                    onClicked: root.showPage(1)
                }

                MimosTabButton {
                    id: aboutTab
                    objectName: "aboutTab"
                    text: "Acerca de"
                    Accessible.name: text
                    onClicked: root.showPage(2)
                }
            }

            StackLayout {
                Layout.fillWidth: true
                Layout.fillHeight: true
                Layout.minimumWidth: 0
                currentIndex: root.currentPage

                ScrollView {
                    id: homePage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: homePage.availableWidth
                        spacing: 16

                        Text {
                            Layout.fillWidth: true
                            text: "Bienvenido a MimOS"
                            color: root.cloud
                            font.pixelSize: 30
                            font.bold: true
                        }

                        Text {
                            objectName: "homeIntro"
                            Layout.fillWidth: true
                            text: root.liveEnvironment
                                  ? "Explora KDE Plasma y conoce el proyecto sin modificar ningún disco."
                                  : "Tu sistema está instalado. Explora KDE Plasma y termina de hacerlo tuyo."
                            color: root.muted
                            font.pixelSize: 16
                            wrapMode: Text.WordWrap
                        }

                        Rectangle {
                            Layout.fillWidth: true
                            implicitHeight: 128
                            radius: 16
                            color: root.panel
                            border.color: "#4C4069"

                            ColumnLayout {
                                anchors.fill: parent
                                anchors.margins: 20
                                spacing: 8

                                Text {
                                    objectName: "contextCardTitle"
                                    text: root.liveEnvironment
                                          ? "Un espacio seguro para probar"
                                          : "Tu nuevo hogar está listo"
                                    color: root.cloud
                                    font.pixelSize: 19
                                    font.bold: true
                                }

                                Text {
                                    objectName: "contextCardBody"
                                    Layout.fillWidth: true
                                    text: root.liveEnvironment
                                          ? "Puedes probar MimOS sin tocar el disco. Si decides instalarlo, el instalador sí modifica el disco que elijas."
                                          : "MimOS ya está instalado. Centro de MimOS no ofrece acciones de particionado ni conserva componentes del instalador."
                                    color: root.muted
                                    font.pixelSize: 14
                                    wrapMode: Text.WordWrap
                                }

                                MimosButton {
                                    id: installerButton
                                    objectName: "installerButton"
                                    visible: root.liveEnvironment
                                    text: "Instalar MimOS"
                                    Accessible.name: text
                                    Accessible.description: "Abre el instalador, que modificará el disco que elijas"
                                    onClicked: root.installerRequested()
                                }
                            }
                        }

                        RowLayout {
                            Layout.fillWidth: true
                            spacing: 14

                            Rectangle {
                                Layout.fillWidth: true
                                implicitHeight: 112
                                radius: 16
                                color: root.panel

                                ColumnLayout {
                                    anchors.fill: parent
                                    anchors.margins: 18

                                    Text {
                                        text: "Privado por defecto"
                                        color: root.calm
                                        font.pixelSize: 17
                                        font.bold: true
                                    }
                                    Text {
                                        Layout.fillWidth: true
                                        text: "Sin telemetría automática ni cuenta obligatoria."
                                        color: root.muted
                                        wrapMode: Text.WordWrap
                                    }
                                }
                            }

                            Rectangle {
                                Layout.fillWidth: true
                                implicitHeight: 112
                                radius: 16
                                color: root.panel

                                ColumnLayout {
                                    anchors.fill: parent
                                    anchors.margins: 18

                                    Text {
                                        text: "Basado en Arch"
                                        color: root.hug
                                        font.pixelSize: 17
                                        font.bold: true
                                    }
                                    Text {
                                        Layout.fillWidth: true
                                        text: "Herramientas conocidas, componentes abiertos y decisiones documentadas."
                                        color: root.muted
                                        wrapMode: Text.WordWrap
                                    }
                                }
                            }
                        }
                    }
                }

                ScrollView {
                    id: privacyPage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: privacyPage.availableWidth
                        spacing: 10

                        Text {
                            Layout.fillWidth: true
                            text: "Privacidad clara, sin letra pequeña"
                            color: root.cloud
                            font.pixelSize: 26
                            font.bold: true
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Estas preferencias se guardan únicamente en tu perfil local. Centro de MimOS no envía ningún dato."
                            color: root.muted
                            font.pixelSize: 15
                            wrapMode: Text.WordWrap
                        }

                        Rectangle {
                            Layout.fillWidth: true
                            implicitHeight: 72
                            radius: 16
                            color: "#183D38"
                            border.color: root.calm

                            RowLayout {
                                anchors.fill: parent
                                anchors.margins: 18
                                spacing: 16

                                Text {
                                    text: "✓"
                                    color: root.calm
                                    font.pixelSize: 28
                                    font.bold: true
                                }

                                ColumnLayout {
                                    Layout.fillWidth: true
                                    Layout.minimumWidth: 0
                                    Text {
                                        text: "Telemetría automática desactivada"
                                        color: root.cloud
                                        font.pixelSize: 17
                                        font.bold: true
                                    }
                                    Text {
                                        Layout.fillWidth: true
                                        Layout.minimumWidth: 0
                                        text: "MimOS no incorpora seguimiento ni subidas silenciosas."
                                        color: root.muted
                                        wrapMode: Text.WordWrap
                                    }
                                }
                            }
                        }

                        PrivacySwitch {
                            id: updatesSwitch
                            objectName: "updatesSwitch"
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Mostrar Centro de MimOS después de una actualización"
                            checked: root.showAfterUpdates
                            Accessible.name: text
                            Accessible.description: "Guarda localmente si debe mostrarse la bienvenida de una versión nueva"
                            onToggled: root.showAfterUpdates = checked
                        }

                        PrivacySwitch {
                            id: hardwareSwitch
                            objectName: "hardwareSwitch"
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Incluir un resumen del hardware en informes manuales"
                            checked: root.includeHardwareDetails
                            Accessible.name: text
                            Accessible.description: "Preferencia local, desactivada inicialmente; todavía no existe un generador de informes"
                            onToggled: root.includeHardwareDetails = checked
                        }

                        PrivacySwitch {
                            id: logsSwitch
                            objectName: "logsSwitch"
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Incluir registros recientes en informes manuales"
                            checked: root.includeRecentLogs
                            Accessible.name: text
                            Accessible.description: "Preferencia local, desactivada inicialmente; todavía no existe un generador de informes"
                            onToggled: root.includeRecentLogs = checked
                        }

                        Text {
                            Layout.fillWidth: true
                            Layout.minimumWidth: 0
                            text: "Los informes de soporte aún no están implementados. Estas opciones solo establecen valores predeterminados para una función futura y nunca autorizan un envío."
                            color: root.muted
                            font.pixelSize: 12
                            wrapMode: Text.WordWrap
                        }

                        MimosButton {
                            id: resetPrivacyButton
                            objectName: "resetPrivacyButton"
                            text: "Restablecer valores privados"
                            Accessible.name: text
                            Accessible.description: "Activa la bienvenida y desactiva la inclusión de hardware y registros"
                            onClicked: root.resetPrivacy()
                        }
                    }
                }

                ScrollView {
                    id: aboutPage
                    Layout.minimumWidth: 0
                    clip: true
                    ScrollBar.horizontal.policy: ScrollBar.AlwaysOff

                    ColumnLayout {
                        width: aboutPage.availableWidth
                        spacing: 18

                        Text {
                            Layout.fillWidth: true
                            text: "MimOS"
                            color: root.cloud
                            font.pixelSize: 34
                            font.bold: true
                        }

                        Text {
                            Layout.fillWidth: true
                            text: "Una distribución Linux basada en Arch"
                            color: root.hug
                            font.pixelSize: 18
                        }

                        Text {
                            Layout.fillWidth: true
                            text: root.liveEnvironment
                                  ? "MimOS busca una experiencia amable, accesible y técnicamente honesta. Esta versión es experimental y el acceso público al instalador permanece en validación."
                                  : "MimOS busca una experiencia amable, accesible y técnicamente honesta. Este sistema instalado es experimental y todavía no está recomendado para uso diario."
                            color: root.muted
                            font.pixelSize: 15
                            wrapMode: Text.WordWrap
                        }

                        Rectangle {
                            Layout.fillWidth: true
                            implicitHeight: 132
                            radius: 16
                            color: root.panel

                            ColumnLayout {
                                anchors.fill: parent
                                anchors.margins: 20
                                spacing: 8

                                Text {
                                    text: "powered by XI14"
                                    color: root.kiss
                                    font.pixelSize: 20
                                    font.bold: true
                                }
                                Text {
                                    text: "David y Jan"
                                    color: root.cloud
                                    font.pixelSize: 16
                                }
                                Text {
                                    Layout.fillWidth: true
                                    text: "El código, las decisiones y la evidencia técnica se mantienen en el repositorio privado del proyecto."
                                    color: root.muted
                                    wrapMode: Text.WordWrap
                                }
                            }
                        }
                    }
                }
            }

            RowLayout {
                Layout.fillWidth: true

                Text {
                    Layout.fillWidth: true
                    text: "Tab navegar · Enter activar · Esc cerrar"
                    color: root.muted
                    font.pixelSize: 12
                }

                MimosButton {
                    id: closeButton
                    objectName: "closeButton"
                    text: "Cerrar"
                    Accessible.name: text
                    onClicked: root.closeRequested()
                }
            }
        }
    }

    Keys.onEscapePressed: event => {
        root.closeRequested()
        event.accepted = true
    }

    Component.onCompleted: Qt.callLater(focusCurrentPage)
}
