// Tienda de MimOS (ADR-152). Installed context only, launched from the
// Centro's «Instalar aplicaciones» card. Same boundary as the Centro
// (ADR-093): this view has NO process, network or file capability -- the
// catalogue is a generated literal, the installed set arrives by argv,
// and the only way anything happens is an exit status the launcher acts
// on. Selection crosses to the launcher through the Settings file, and
// the launcher re-validates every token against the shipped allowlist
// before a single name reaches a command line.
//
// Navigation is the Centro's own shape (David's call, ADR-152 addendum):
// a front page of category cards, one page per category, and a footer
// that keeps the running selection visible everywhere -- so marking apps
// across categories feels like one basket, not five lists.
pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Item {
    id: root

    objectName: "tiendaView"
    width: 900
    height: 640
    focus: true

    property bool darkAppearance: false
    // Space-separated pacman names the launcher found already installed.
    property string instaladas: ""
    // Written just before the install exit so the Settings alias in
    // TiendaWindow.qml persists it for the launcher to read back.
    property string seleccionPendiente: ""

    // 0 = portada (category cards), 1 = one category's list.
    property int paginaActual: 0
    property string categoriaActual: ""

    signal closeRequested()
    signal instalarRequested()
    signal busquedaAvanzadaRequested()

    // mimos-palette-begin
    // Generated by scripts/generate-color-schemes.py from
    // packages/mimos-branding/palette.json. Do not edit by hand;
    // claro values come from the mimos-claro roles and oscuro from
    // mimos-oscuro; the launcher picks the side via
    // --mimos-appearance (ADR-093).
    readonly property color ground: root.darkAppearance ? "#221B3A" : "#FFE9F3"
    readonly property color panel: root.darkAppearance ? "#2C2444" : "#FFD3E5"
    readonly property color panelRaised: root.darkAppearance ? "#3A3058" : "#FFFFFF"
    readonly property color ink: root.darkAppearance ? "#F8F4FF" : "#221B3A"
    readonly property color inkMuted: root.darkAppearance ? "#B6ADCE" : "#7A5670"
    readonly property color hug: root.darkAppearance ? "#B3A2FF" : "#5B3BE0"
    readonly property color kiss: "#FF6FAE"
    readonly property color calm: root.darkAppearance ? "#70D6C5" : "#136B5B"
    // mimos-palette-end

    readonly property color edge: Qt.alpha(root.ink, 0.14)

    // mimos-catalogo-begin
    // Generated by scripts/generate-tienda-catalogo.py from
    // packages/mimos-welcome/mimos-aplicaciones.json. Do not edit
    // by hand; the launcher validates selections against the same
    // canonical file's flat derivation (ADR-152).
    readonly property var categorias: ["Internet", "Fotos y dibujo", "Música y vídeo", "Juegos", "Utilidades"]
    readonly property var catalogo: [
        {"paquete": "thunderbird", "nombre": "Thunderbird", "descripcion": "Correo electrónico en tu escritorio, de los creadores de Firefox", "categoria": "Internet"},
        {"paquete": "discord", "nombre": "Discord", "descripcion": "Chat de voz y texto para comunidades y amigos", "categoria": "Internet"},
        {"paquete": "signal-desktop", "nombre": "Signal", "descripcion": "Mensajería privada y cifrada", "categoria": "Internet"},
        {"paquete": "telegram-desktop", "nombre": "Telegram", "descripcion": "La mensajería de Telegram, en grande y con teclado", "categoria": "Internet"},
        {"paquete": "qbittorrent", "nombre": "qBittorrent", "descripcion": "Descargas por BitTorrent, sin anuncios", "categoria": "Internet"},
        {"paquete": "gimp", "nombre": "GIMP", "descripcion": "Edición de imágenes y fotografía, el clásico libre", "categoria": "Fotos y dibujo"},
        {"paquete": "inkscape", "nombre": "Inkscape", "descripcion": "Dibujo vectorial: logotipos, carteles, diseños", "categoria": "Fotos y dibujo"},
        {"paquete": "krita", "nombre": "Krita", "descripcion": "Pintura digital e ilustración", "categoria": "Fotos y dibujo"},
        {"paquete": "darktable", "nombre": "darktable", "descripcion": "Revelado de fotos RAW, como un cuarto oscuro digital", "categoria": "Fotos y dibujo"},
        {"paquete": "digikam", "nombre": "digiKam", "descripcion": "Organiza y etiqueta miles de fotos", "categoria": "Fotos y dibujo"},
        {"paquete": "kdenlive", "nombre": "Kdenlive", "descripcion": "Edición de vídeo completa y libre", "categoria": "Música y vídeo"},
        {"paquete": "obs-studio", "nombre": "OBS Studio", "descripcion": "Graba tu pantalla o emite en directo", "categoria": "Música y vídeo"},
        {"paquete": "audacity", "nombre": "Audacity", "descripcion": "Grabación y edición de audio", "categoria": "Música y vídeo"},
        {"paquete": "handbrake", "nombre": "HandBrake", "descripcion": "Convierte vídeos entre formatos", "categoria": "Música y vídeo"},
        {"paquete": "vlc", "nombre": "VLC", "descripcion": "El reproductor que lo reproduce todo", "categoria": "Música y vídeo"},
        {"paquete": "steam", "nombre": "Steam", "descripcion": "La mayor tienda de juegos de PC", "categoria": "Juegos"},
        {"paquete": "supertuxkart", "nombre": "SuperTuxKart", "descripcion": "Karts con Tux: carreras para toda la familia", "categoria": "Juegos"},
        {"paquete": "luanti", "nombre": "Luanti", "descripcion": "Construye mundos de bloques (antes Minetest)", "categoria": "Juegos"},
        {"paquete": "gcompris-qt", "nombre": "GCompris", "descripcion": "Más de cien actividades educativas para peques", "categoria": "Juegos"},
        {"paquete": "keepassxc", "nombre": "KeePassXC", "descripcion": "Guarda tus contraseñas bajo llave", "categoria": "Utilidades"},
        {"paquete": "filelight", "nombre": "Filelight", "descripcion": "Descubre qué está llenando tu disco", "categoria": "Utilidades"},
        {"paquete": "kdf", "nombre": "KDiskFree", "descripcion": "Vigila el espacio libre de tus discos", "categoria": "Utilidades"},
        {"paquete": "code", "nombre": "Code", "descripcion": "Editor de código para programar (VS Code libre)", "categoria": "Utilidades"}
    ]
    // mimos-catalogo-end

    readonly property var instaladasSet: {
        const set = {};
        const nombres = root.instaladas.trim();
        if (nombres.length > 0) {
            for (const nombre of nombres.split(" ")) {
                set[nombre] = true;
            }
        }
        return set;
    }

    property int seleccionadas: 0

    // Presentation only: a category glyph is not catalogue data.
    function glifoCategoria(categoria) {
        switch (categoria) {
        case "Internet": return "🌐";
        case "Fotos y dibujo": return "🎨";
        case "Música y vídeo": return "🎬";
        case "Juegos": return "🎮";
        case "Utilidades": return "🧰";
        default: return "📦";
        }
    }

    function cuentaCategoria(categoria) {
        let cuenta = 0;
        for (const app of root.catalogo) {
            if (app.categoria === categoria) {
                cuenta += 1;
            }
        }
        return cuenta;
    }

    function abreCategoria(categoria) {
        root.categoriaActual = categoria;
        root.paginaActual = 1;
    }

    function vuelvePortada() {
        root.paginaActual = 0;
        root.categoriaActual = "";
    }

    function recuentaSeleccion() {
        let cuenta = 0;
        let nombres = [];
        for (let i = 0; i < filas.count; i++) {
            const fila = filas.get(i);
            if (fila.marcado && !fila.instalada) {
                cuenta += 1;
                nombres.push(fila.paquete);
            }
        }
        root.seleccionadas = cuenta;
        root.seleccionPendiente = nombres.join(" ");
    }

    ListModel {
        id: filas
    }

    Component.onCompleted: {
        for (const app of root.catalogo) {
            filas.append({
                paquete: app.paquete,
                nombre: app.nombre,
                descripcion: app.descripcion,
                categoria: app.categoria,
                instalada: root.instaladasSet[app.paquete] === true,
                marcado: root.instaladasSet[app.paquete] === true
            });
        }
    }

    Keys.onEscapePressed: {
        if (root.paginaActual === 1) {
            root.vuelvePortada();
        } else {
            root.closeRequested();
        }
    }

    component MimosButton: Button {
        id: control

        implicitHeight: 40
        leftPadding: 18
        rightPadding: 18
        font.bold: true
        Keys.onReturnPressed: control.clicked()
        Keys.onEnterPressed: control.clicked()

        contentItem: Text {
            text: control.text
            color: control.enabled ? root.ink : root.inkMuted
            font: control.font
            horizontalAlignment: Text.AlignHCenter
            verticalAlignment: Text.AlignVCenter
        }

        background: Rectangle {
            radius: 10
            color: control.down ? root.panel
                                : control.hovered ? root.panelRaised
                                                  : root.panel
            border.color: control.activeFocus ? root.calm : root.edge
            border.width: control.activeFocus ? 2 : 1
        }
    }

    component TarjetaCategoria: Button {
        id: control

        required property string categoria

        implicitHeight: 128
        Layout.fillWidth: true
        Layout.preferredWidth: 1
        Accessible.name: control.categoria
        Accessible.description:
            root.cuentaCategoria(control.categoria) + " aplicaciones"
        Keys.onReturnPressed: control.clicked()
        Keys.onEnterPressed: control.clicked()
        onClicked: root.abreCategoria(control.categoria)

        contentItem: ColumnLayout {
            spacing: 6

            Text {
                Layout.alignment: Qt.AlignHCenter
                text: root.glifoCategoria(control.categoria)
                font.pixelSize: 34
            }

            Text {
                Layout.alignment: Qt.AlignHCenter
                Layout.fillWidth: true
                text: control.categoria
                color: root.ink
                font.pixelSize: 15
                font.bold: true
                horizontalAlignment: Text.AlignHCenter
                wrapMode: Text.WordWrap
            }

            Text {
                Layout.alignment: Qt.AlignHCenter
                text: root.cuentaCategoria(control.categoria) + " aplicaciones"
                color: root.inkMuted
                font.pixelSize: 12
            }
        }

        background: Rectangle {
            radius: 16
            color: control.down ? root.panel
                                : control.hovered ? root.panelRaised
                                                  : root.panel
            border.color: control.activeFocus ? root.calm : root.edge
            border.width: control.activeFocus ? 2 : 1
        }
    }

    Rectangle {
        anchors.fill: parent
        color: root.ground
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 24
        spacing: 14

        RowLayout {
            Layout.fillWidth: true
            spacing: 12

            MimosButton {
                objectName: "botonVolver"
                text: "‹ Volver"
                visible: root.paginaActual === 1
                onClicked: root.vuelvePortada()
            }

            Text {
                text: root.paginaActual === 1
                    ? root.categoriaActual
                    : "Tienda de MimOS"
                color: root.ink
                font.pixelSize: 26
                font.bold: true
            }

            Rectangle {
                radius: 8
                color: root.panel
                implicitHeight: badge.implicitHeight + 8
                implicitWidth: badge.implicitWidth + 16

                Text {
                    id: badge
                    anchors.centerIn: parent
                    text: "repos oficiales de Arch"
                    color: root.inkMuted
                    font.pixelSize: 11
                    font.bold: true
                }
            }

            Item { Layout.fillWidth: true }
        }

        StackLayout {
            Layout.fillWidth: true
            Layout.fillHeight: true
            currentIndex: root.paginaActual

            // --- Portada: una tarjeta por categoría -------------------------
            ColumnLayout {
                spacing: 14

                Text {
                    Layout.fillWidth: true
                    text: "Elige una categoría, marca lo que quieras y pulsa "
                          + "instalar: verás lo que ocurre en un terminal, con "
                          + "tu contraseña por delante y una instantánea por "
                          + "debajo."
                    color: root.inkMuted
                    font.pixelSize: 13
                    wrapMode: Text.WordWrap
                }

                GridLayout {
                    objectName: "tarjetasCategorias"
                    Layout.fillWidth: true
                    columns: 3
                    rowSpacing: 12
                    columnSpacing: 12

                    Repeater {
                        model: root.categorias

                        TarjetaCategoria {
                            required property string modelData
                            categoria: modelData
                        }
                    }
                }

                Item { Layout.fillHeight: true }
            }

            // --- Una categoría: su lista con casillas -----------------------
            ListView {
                id: lista

                objectName: "listaCatalogo"
                clip: true
                spacing: 4
                model: filas

                ScrollBar.vertical: ScrollBar { }

                delegate: CheckDelegate {
                    id: fila

                    required property int index
                    required property string paquete
                    required property string nombre
                    required property string descripcion
                    required property string categoria
                    required property bool instalada
                    required property bool marcado

                    readonly property bool enCategoria:
                        fila.categoria === root.categoriaActual

                    width: lista.width - 12
                    visible: fila.enCategoria
                    height: fila.enCategoria ? implicitHeight : 0
                    checked: fila.marcado
                    enabled: !fila.instalada
                    Accessible.name: fila.nombre
                    Accessible.description: fila.instalada
                        ? fila.descripcion + " (ya instalada)"
                        : fila.descripcion

                    onToggled: {
                        filas.setProperty(fila.index, "marcado", fila.checked);
                        root.recuentaSeleccion();
                    }

                    contentItem: ColumnLayout {
                        spacing: 2

                        Text {
                            Layout.fillWidth: true
                            text: fila.instalada
                                ? fila.nombre + " · ya en tu MimOS"
                                : fila.nombre
                            color: fila.instalada ? root.inkMuted : root.ink
                            font.pixelSize: 14
                            font.bold: true
                            elide: Text.ElideRight
                        }

                        Text {
                            Layout.fillWidth: true
                            text: fila.descripcion
                            color: root.inkMuted
                            font.pixelSize: 12
                            wrapMode: Text.WordWrap
                        }
                    }

                    background: Rectangle {
                        radius: 10
                        color: fila.down ? root.panel
                                         : fila.hovered ? root.panelRaised
                                                        : "transparent"
                        border.color: fila.activeFocus ? root.calm : "transparent"
                        border.width: fila.activeFocus ? 2 : 0
                    }
                }
            }
        }

        RowLayout {
            Layout.fillWidth: true
            spacing: 10

            MimosButton {
                objectName: "botonInstalar"
                text: root.seleccionadas > 0
                    ? "Instalar seleccionadas (" + root.seleccionadas + ")"
                    : "Instalar seleccionadas"
                enabled: root.seleccionadas > 0
                onClicked: root.instalarRequested()
            }

            MimosButton {
                objectName: "botonAvanzado"
                text: "¿No está lo que buscas? Todo el catálogo…"
                onClicked: root.busquedaAvanzadaRequested()
            }

            Item { Layout.fillWidth: true }

            MimosButton {
                objectName: "botonCerrar"
                text: "Cerrar"
                onClicked: root.closeRequested()
            }
        }
    }
}
